name: Format check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  merge_group:

jobs:
  format-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository for the qlever script
        uses: actions/checkout@v6

      - name: Setup linter and formatter
        uses: astral-sh/ruff-action@v4.0.0
      - name: lint
        run: ruff check
        id: lint
        continue-on-error: true
      - name: format
        run: ruff format --diff
        id: format
        continue-on-error: true
      - name: fail if any check failed
        if: steps.lint.outcome == 'failure' || steps.format.outcome == 'failure'
        run: exit 1
